/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = [''];
//# sourceMappingURL=hello.component.css.shim.ngstyle.js.map